### ISSUE TITLE
Сделать возможность того, что бы бот со 100% вероятностью хуифицировал реплаи его сообщений

### ISSUE THREAD

**Issue by necto68** [m-messiah/xye-bot#14]
Иногда люди огрызаются на бота через реплай его сообщений.
Данная функция добавит боту возможность огрызаться в ответ со 100%-ой вероятностью.

**Comment by m-messiah** [comment]
Хм, интересная идея.

**Comment by necto68** [comment]
Причем лучше сделать тоже через реплай.
Эдакая перепалка между юзером и ботом. :)
