### ISSUE TITLE
Бот стал слишком вежливым

### ISSUE THREAD

**Issue by rinatkhaziev** [m-messiah/xye-bot#4]
Надо убрать Suggestions, слишком ванильно, потерял авторитет.

**Comment by m-messiah** [comment]
Людям нравится. В ближайшее время сделаю их включение/выключение по команде.

**Comment by rinatkhaziev** [comment]
@m-messiah, ясно, было бы неплохо. Вчера хотел установить, попробовать, но вообще не нашел настроек урл/токена, подумал, что остальное лежит где-то в манифесте, это так? 

Если да, можно пример?

**Comment by m-messiah** [comment]
@rinatkhaziev нигде не лежит - слушает корень, токен для этого не нужен.
