### ISSUE TITLE
Игнор междометий

### ISSUE THREAD

**Issue by m-messiah** [m-messiah/xye-bot#8]
Стоит ли игнорировать междометия и "хахаха"? По идее бот итак пропускает короткие слова, а если слово длинное, то вполне вероятно, что и результат получится интересным.

В общем, хотелось бы увидеть какие-то примеры слов, которые стоит игнорировать, если вообще стоит.

**Comment by SlavMetal** [comment]
Сообщения вроде "хахаха" действительно было бы неплохо блокировать. В целом, имхо, текущих ограничений полностью хватает.

**Comment by FukkenBro** [comment]
Also было бы неплохо добавить переменную для случайного выбора кол-ва последних слов в сообщении которые он бы изменял.
